name: Publish Docker Image

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve repository name
        run: |
          echo "REPOSITORY_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Free disk space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construct image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          build-args: |
            IPEXLLM_RELEASE_REPO=ipex-llm/ipex-llm
            IPEXLLM_RELEASE_VERSON=v2.3.0-nightly
            IPEXLLM_PORTABLE_ZIP_FILENAME=ollama-ipex-llm-2.3.0b20250415-ubuntu.tgz
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ steps.meta.outputs.tags }}
